config/routes.rb
Rails.application.routes.draw do
  mount Parse::Webhooks, at: '/webhooks'
  root 'home#index'

  resources :accidents
  resources :statuses
  resources :areas
  resources :employees
  resources :companies
  resources :nonconformities
  resources :company_notifications

  get 'finish_action/:id' => 'nonconformities#finish_action', as: 'finish_nonconformity'
  get 'finish_action_accident/:id' => 'accidents#finish_action', as: 'finish_accident'
  get 'users' => 'home#list_users'
  get 'logout' => 'user#end_session'
  get 'convert/:base64' => 'home#convert_base_64'
  get 'sign_in' => 'user#sign_in'
  get 'sign_up' => 'user#sign_up'

  post 'sign_up' => 'user#create_user'
  post 'sign_in' => 'user#create_session'

  delete 'eliminar-usuario/:id' => 'user#delete_user', as: 'delete_user'
end

app/models/employee.rb
class Employee < Parse::Object
  # See: https://github.com/modernistik/parse-stack#defining-properties

  # You can change the inferred Parse table/collection name below
  # parse_class "Area"

  property :first_name, :string
  property :last_name, :string
  property :rut, :string
  property :email, :string
  property :phone, :string
  belongs_to :company
  has_many :accidents
  has_many :nonconformities
  property :can_view_all_areas, :boolean


  def full_name
    "#{first_name} #{last_name}"
  end

  def see_company_id
    "#{company.id}"
  end
  # See: https://github.com/modernistik/parse-stack#cloud-code-webhooks

  ## define an after save webhook for Area
  #
  # webhook :after_save do
  #   area = parse_object
  #
  # end

  ## define a before delete webhook for Area
  # webhook :before_delete do
  #   area = parse_object
  #   # use `error!(msg)` to fail the delete
  #   true # allow the deletion
  # end

  ## define an after delete webhook for Area
  # webhook :after_delete do
  #   area = parse_object
  # end

  ## Example of a CloudCode Webhook function
  ## define a `helloWorld` Parse CloudCode function
  # webhook :function, :helloWorld do
  #   "Hello!"
  # end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[show edit update destroy]
  before_action :set_user
  layout 'admin'
  require 'will_paginate/array'

  # GET /employees
  # GET /employees.json
  def index
    i_am_admin? ? @employees = Parse::Query.new('Employee') : @employees = @user.company.employees.all
    @employees.where :company.id => params[:company_id] if params[:company_id].present?
    @employees.where :company.id => @user.company.id if !@user.is_admin && @employees.class.to_s == 'Parse::Query'
    @employees.where :first_name.like => params[:name].to_s if params[:name].present?
    @employees.sort_by(&:first_name)
    @employees = @employees.result if @employees.class.to_s == 'Parse::Query'
    @employees = @employees.paginate(page: params[:page], per_page: 20)
    @companies = Company.all
    @companies = Parse::Query.new('Company').where id: @user.company.id
  end

  # GET /employees/1
  # GET /employees/1.json
  def show; end

  # GET /employees/new
  def new
    @companies = Company.all if @user.is_admin
    @companies = Parse::Query.new('Company').where id: @user.company.id if @user.is_supervisor
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
    @companies = Company.all if @user.is_admin
    @companies = Parse::Query.new('Company').where id: @user.company.id if @user.is_supervisor
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)
    @employee.company = Company.find(params[:employee][:company])
    @employee.can_view_all_areas = false if @employee.can_view_all_areas.nil?
    respond_to do |format|
      if @employee.save
        format.html { redirect_to employee_path(@employee), notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      @employee.first_name = params[:employee][:first_name]
      @employee.last_name = params[:employee][:last_name]
      @employee.email =  params[:employee][:email]
      @employee.phone =  params[:employee][:phone]
      @employee.rut = params[:employee][:rut]
      @employee.company = Company.find(params[:employee][:company])
      @employee.can_view_all_areas = params[:employee][:can_view_all_areas]
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = Employee.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def employee_params
    # Parse server dont allow strong parameters
    data = {
      first_name: params[:employee][:first_name],
      last_name: params[:employee][:last_name],
      email: params[:employee][:email],
      phone: params[:employee][:phone],
      rut: params[:employee][:rut],
      company: params[:employee][:company],
      can_view_all_areas: params[:employee][:can_view_all_areas]
    }
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
				<li class="">Inicio</li>
				<li class="active">Empleado</li>
			</ol>
		</div><!--/.row-->
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Empleado</h1>
			</div>
		</div><!--/.row-->

    <%= form_for @employee do |form| %>

      <div class="container">
			<div class="row main">
				<div class="panel-heading">
				<div class="main-login main-center">
					<form class="form-horizontal" method="post" action="#">

						<div class="form-group">
							<label for="name" class="cols-sm-2 control-label">Nombre</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="glyphicon glyphicon-user" aria-hidden="true"></i></span>
                    <%= form.text_field :first_name, class:'form-control' , required:"true"  %>
  								</div>
							</div>
						</div>

						<div class="form-group">
							<label for="email" class="cols-sm-2 control-label">Apellido</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="glyphicon glyphicon-user" aria-hidden="true"></i></span>
                    <%= form.text_field :last_name, class:'form-control', required:"true"  %>
								</div>
							</div>
						</div>

						<div class="form-group">
							<label for="username" class="cols-sm-2 control-label">RUT (Sin guión ni punto)</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i></span>
                  <%= form.text_field :rut, class:'form-control', required:"true"  %>
								</div>
							</div>
						</div>


						<div class="form-group">
							<label for="username" class="cols-sm-2 control-label">Email</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i></span>
                  <%= form.text_field :email, class:'form-control' %>
								</div>
							</div>
						</div>

						<div class="form-group">
							<label for="username" class="cols-sm-2 control-label">Teléfono</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i></span>
                  <%= form.text_field :phone, class:'form-control' %>
								</div>
							</div>
						</div>

						<div class="form-group">
							<label for="username" class="cols-sm-2 control-label">Compañía</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="glyphicon glyphicon-briefcase" aria-hidden="true"></i></span>
                  <%= form.collection_select :company, @companies, :id, :name, {prompt:true}, {required: true}%>
								</div>
							</div>
						</div>
							<div class="form-group">
							  Dar acceso a todas las áreas?
								<%= form.check_box :can_view_all_areas, {class:"form-control"}, true,false %>
							</div>
						<div class="login-register">
                <%= form.submit 'Guardar', class:'btn btn-success'%>
                 <%= link_to 'Volver', employees_path, class:'btn btn-warning' %>
				    </div>
					</form>
				</div>
			</div>
		</div>
    <%end%>
			</div><!--/.col-->
		</div><!--/.row-->
	</div>	<!--/.main-->

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
				<li class="">Inicio</li>
				<li class="active">Empleados</li>
			</ol>
		</div><!--/.row-->

		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Empleados</h1>
			</div>
		</div><!--/.row-->
    <% if i_am_admin? || i_am_supervisor? || @user.can_view_all %>
        <div class="row">

          <div class="col-md-12">

            <div class="panel panel-default">
              <div class="panel-heading">
                Filtrar Resultados
              </div>
              <%= form_tag(employees_path, {:method => 'get'}) do %>
                  <div class="panel-body">

                    <div class="row">
                      <div class="col-md-0"></div>
                      <div class="col-md-2 col-sm-4">
                        Nombre:<br>
                        <%= text_field_tag :name, nil, {class:'form-control'} %>
                      </div>
                      <div class="col-md-2 col-sm-4">
                        Compañía:<br>
                        <%= select_tag :company_id , options_from_collection_for_select(@companies, :id, :name, selected: params[:company_id]), include_blank: "Todas", class: "input-sm form-control" %>
                      </div>
                      <div class="col-md-2">
                        <br>
                        <%= submit_tag('Buscar', :name => nil, class:"btn btn-default btn-sm") %>
                      </div>
                    </div><!-- /.row -->
                  </div>
              <% end%>
            </div>
          </div>
        </div>

    <% end %>
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th>Nombres</th>
                      <th>Apellidos</th>
                      <th>RUT</th>
                      <th>Email</th>
                      <th>Teléfono</th>
                      <th>Compañía</th>
                      <th colspan="3">Acciones</th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @employees.each do |employee| %>
                      <tr>
                        <td><%=employee.first_name%></td>
                        <td><%=employee.last_name%></td>
                        <td><%=employee.rut%></td>
                        <td><%=employee.email%></td>
                        <td><%=employee.phone%></td>
                        <td><%=employee.try(:company).try(:name)%></td>
                        <td><center><%= link_to 'Ver', employee, class:"btn btn-success" %></td>
                        <td><center><%= link_to 'Editar', edit_employee_path(employee), class:"btn btn-warning" %></td>
                        <td><center><%= link_to 'Eliminar', employee, method: :delete, data: { confirm: 'Estas seguro?' }, class:"btn btn-danger" %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
                <br>
    <center><%= will_paginate @employees %></center>
    <%= link_to 'Nuevo empleado', new_employee_path , class:'btn btn-success margin-bottom-2'%>
  </div>
<p id="notice"><%= notice %></p>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
				<li class="">Inicio</li>
				<li class="active">Empleado</li>
			</ol>
		</div><!--/.row-->


<p id="notice"><%= notice %></p>

<div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title"><%= @employee.first_name %> <%= @employee.last_name %></h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class="col-md-3 col-lg-3 " align="center"></div>
                <div class=" col-md-9 col-lg-9 ">
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td>RUT:</td>
                        <td><%= @employee.rut %></td>
                      </tr>
                      <tr>
                        <td>Email:</td>
                        <td><%= @employee.email %></td>
                      </tr>
                      <tr>
                        <td>Teléfono:</td>
                        <td><%= @employee.phone %></td>
                      </tr>
                      <tr>
                        <td>Compañía:</td>
                        <td><%= @employee.company.try(:name) %></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
               </div>
              </div>
             <div class="panel-footer">
						  <%= link_to 'Editar', edit_employee_path(@employee) %> |
      				<%= link_to 'Volver', employees_path %>
          	</div>
          </div>
        </div>
      </div>
    </div>