config/routes.rb
Rails.application.routes.draw do
  mount Parse::Webhooks, at: '/webhooks'
  root 'home#index'

  resources :accidents
  resources :statuses
  resources :areas
  resources :employees
  resources :companies
  resources :nonconformities
  resources :company_notifications

  get 'finish_action/:id' => 'nonconformities#finish_action', as: 'finish_nonconformity'
  get 'finish_action_accident/:id' => 'accidents#finish_action', as: 'finish_accident'
  get 'users' => 'home#list_users'
  get 'logout' => 'user#end_session'
  get 'convert/:base64' => 'home#convert_base_64'
  get 'sign_in' => 'user#sign_in'
  get 'sign_up' => 'user#sign_up'

  post 'sign_up' => 'user#create_user'
  post 'sign_in' => 'user#create_session'

  delete 'eliminar-usuario/:id' => 'user#delete_user', as: 'delete_user'
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]
  before_action :set_user
  layout 'admin'

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      @status.name = params[:status][:name]
      @status.description = params[:status][:description]
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      #Parse server dont allow strong parameters
      data = {
        name: params[:status][:name],
        description: params[:status][:description]
      }
    end
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/statuses/_form.html.erb
<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
				<li class="">Inicio</li>
				<li class="active">Estados</li>
			</ol>
		</div><!--/.row-->
    <center>
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Estados</h1>
			</div>
		</div><!--/.row-->
<%= form_for @status do |form| %>
     <div class="container">
			<div class="row main">
				<div class="panel-heading">
				<div class="main-login main-center">
					<form class="form-horizontal" method="post" action="#">

						<div class="form-group">
							<label for="name" class="cols-sm-2 control-label">Estado</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="glyphicon glyphicon-info-sign" aria-hidden="true"></i></span>
                    <%= form.text_field :name, class:'form-control', required:true %>
  								</div>
							</div>
						</div>

						<div class="form-group">
							<label for="email" class="cols-sm-2 control-label">Descripcion</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="glyphicon glyphicon-comment" aria-hidden="true"></i></span>
                    <%= form.text_field :description, class:'form-control' %>
								</div>
							</div>
						</div>

						<div class="login-register">
                <%= form.submit 'Guardar', class:'btn btn-success'%>
                 <%= link_to 'Volver', statuses_path, class:'btn btn-warning' %>
				    </div>
					</form>
				</div>
			</div>
		</div>
    <%end%>
            </div>
        <br>
			</div><!--/.col-->
		</div><!--/.row-->
	</div>	<!--/.main-->

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<p id="notice"><%= notice %></p>
	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
				<li class="">Inicio</li>
				<li class="active">Estados</li>
			</ol>
		</div><!--/.row-->

		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Estados</h1>
			</div>
		</div><!--/.row-->
      <table class="table  table-bordered">
        <thead>
          <tr>
            <th>Nombre</th>
            <th>Descripción</th>
            <th colspan="3">Acciones</th>
          </tr>
        </thead>

        <tbody>
          <% @statuses.each do |status| %>
            <tr>
              <td><%= status.name %></td>
              <td><%= status.description %></td>
              <td><center><%= link_to 'Ver', status, class:'btn btn-success' %></td>
              <td><center><%= link_to 'Editar', edit_status_path(status), class:'btn btn-warning' %></td>
              <td><center><%= link_to 'Eliminar', status, method: :delete, data: { confirm: 'Estas seguro?' }, class:'btn btn-danger' %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
        <%= link_to 'Nuevo estado', new_status_path, class:'btn btn-success'%>
            </div>
        <br>
			</div><!--/.col-->
		</div><!--/.row-->
	</div>	<!--/.main-->

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
				<li class="">Inicio</li>
				<li class="active">Estados</li>
			</ol>
		</div><!--/.row-->
    <center>
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Estados</h1>
			</div>
		</div><!--/.row-->
      <table class="table  table-bordered">
        <thead>
          <tr>
          Nombre: <%= @status.name %><br>
          Descripción: <%= @status.description %><br>
          <%= link_to 'Editar', edit_status_path(@status) %> |
          <%= link_to 'Volver', statuses_path %>
        </div>
        <br>
			</div><!--/.col-->
		</div><!--/.row-->
	</div>	<!--/.main-->
  </center>