config/routes.rb
Rails.application.routes.draw do
  mount Parse::Webhooks, at: '/webhooks'
  root 'home#index'

  resources :accidents
  resources :statuses
  resources :areas
  resources :employees
  resources :companies
  resources :nonconformities
  resources :company_notifications

  get 'finish_action/:id' => 'nonconformities#finish_action', as: 'finish_nonconformity'
  get 'finish_action_accident/:id' => 'accidents#finish_action', as: 'finish_accident'
  get 'users' => 'home#list_users'
  get 'logout' => 'user#end_session'
  get 'convert/:base64' => 'home#convert_base_64'
  get 'sign_in' => 'user#sign_in'
  get 'sign_up' => 'user#sign_up'

  post 'sign_up' => 'user#create_user'
  post 'sign_in' => 'user#create_session'

  delete 'eliminar-usuario/:id' => 'user#delete_user', as: 'delete_user'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_user
  layout 'admin'
  def index
    @non_conformities = Nonconformity.all order: [:created_at.desc]
    @non_conformities = @non_conformities.map(&:month)
    @non_conformities = @non_conformities.uniq.inject([]){|r, i| r << { i => @non_conformities.select{ |b| b == i }.size } }

    @accidents = Accident.all order: [:created_at.desc]
    @accidents = @accidents.map(&:month)
    @accidents = @accidents.uniq.inject([]){|r, i| r << { i => @accidents.select{ |b| b == i }.size } }
  end

  def list_users
    @users = Parse::User.where :company.id => @user.company.id if @user.is_supervisor
    @users = Parse::User if @user.is_admin
    @users = @users.where :email.not => @user.email
  end

  def convert_base_64()
    require "base64"
    decode_base64_content = Base64.decode64("")
    File.open("Output.png", "wb") do |f|
      f.write(decode_base64_content)
    end
  end


end

app/helpers/home_helper.rb
module HomeHelper
  def bool_to_s_permissions(user)
    if(user.is_admin)
      "Administrador"
    elsif(user.is_supervisor)
      "Supervisor"
    else
      "Usuario"
    end
  end
end

app/views/home/_navbar.html.erb
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#"><span>Ultramar</span>App</a>
				<ul class="user-menu">
					<li class="dropdown pull-right">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> <%=@user.email%> <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
							<li><%= link_to "Cerrar sesión", logout_path%></li>
						</ul>
					</li>
				</ul>
			</div>

		</div><!-- /.container-fluid -->
	</nav>

	<div id="sidebar-collapse" clas

app/views/home/_sidebar.html.erb
<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
		<ul class="nav menu">
			<li <%= current_page?(root_path) ? "class=active" : "'"%> ><a href="<%=root_path%>"><svg class="glyph stroked dashboard-dial"><use xlink:href="#stroked-dashboard-dial"></use></svg> Inicio</a></li>
			<li <%= current_page?(accidents_path) ? "class=active" : "'"%>><a href="<%=accidents_path%>"><svg class="glyph stroked line-graph"><use xlink:href="#stroked-line-graph"></use></svg> Incidentes</a></li>
			<li <%= current_page?(nonconformities_path) ? "class=active" : "'"%>><a href="<%=nonconformities_path%>"><svg class="glyph stroked line-graph"><use xlink:href="#stroked-line-graph"></use></svg> No conformidad</a></li>
      <%if i_am_admin? || i_am_supervisor? %>
        <li <%= current_page?(employees_path) ? "class=active" : "'"%>><a href="<%=employees_path%>"><svg class="glyph stroked calendar"><use xlink:href="#stroked-calendar"></use></svg> Empleados</a></li>
				<li <%= current_page?(areas_path) ? "class=active" : "'"%>><a href="<%=areas_path%>"><svg class="glyph stroked line-graph"><use xlink:href="#stroked-line-graph"></use></svg> Áreas</a></li>
				<% if i_am_admin? %>
          <li <%= current_page?(companies_path) ? "class=active" : "'"%>><a href="<%=companies_path%>"><svg class="glyph stroked line-graph"><use xlink:href="#stroked-line-graph"></use></svg>Compañías</a></li>
        <% end %>
        <li <%= current_page?(users_path) ? "class=active" : "'"%>><a href="<%=users_path%>"><svg class="glyph stroked line-graph"><use xlink:href="#stroked-line-graph"></use></svg>Usuarios</a></li>
			<%end%>
			<li role="presentation" class="divider"></li>
		<div class="attribution"><%=notice%></div>
	</div><!--/.sidebar-->

app/views/home/index.html.erb
	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
				<li class="active">Inicio</li>
			</ol>
		</div><!--/.row-->

		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Dashboard</h1>
			</div>
		</div><!--/.row-->
    <canvas id="myChart"></canvas>
			</div><!--/.col-->
		</div><!--/.row-->
  <script>
          var months_nonconformities = [<% @non_conformities.each do |acc|%>
                                           <%="#{acc.first.first-1},"%>
                                        <%end%>];
          var nonconfirmities = [<% @non_conformities.each do |acc|%>
                                      <%="#{acc.first.last},"%>
                                    <%end%>];
          var months_accidents = [<% @accidents.each do |acc|%>
              <%="#{acc.first.first-1},"%>
              <%end%>];
          var accidents = [<% @accidents.each do |acc|%>
              <%="#{acc.first.last},"%>
              <%end%>];

          data_to_accidents = order_custom_to_array(months_accidents, accidents);
          data_to_nonc = order_custom_to_array(months_nonconformities, nonconfirmities);
          new Chart(document.getElementById("myChart"), {
          type: 'line',
          data: {
              labels: ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre', 'Noviembre', 'Diciembre'],
              datasets: [{
                  data: data_to_accidents,
                  label: "No conformidades",
                  borderColor: "#0045cd",
                  fill: false
              }, {
                  data: data_to_nonc,
                  label: "Incidentes",
                  borderColor: "#a20012",
                  fill: false
              }
              ]
          },
          options: {
              title: {
                  display: true,
                  text: 'Incidentes y Noconformidades'
              }
          }
      });

          function order_custom_to_array(positions, values){
              arr = fill_array(new Array(11));
              for(var i = 0; i < positions.length; i++){
                  arr[positions[i]] = values[i];
              }
              return arr;
          }

          function fill_array(arr){
              for(var i = 0; i < arr.length; i++){
                  arr[i] = 0;
              }
              return arr;
          }
  </script>
	</div>	<!--/.main-->

app/views/home/list_users.html.erb
<p id="notice"><%= notice %></p>

	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
				<li class="">Inicio</li>
				<li class="active">Usuarios</li>
			</ol>
		</div><!--/.row-->

		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Usuarios</h1>
			</div>
		</div><!--/.row-->
                <table class="table table-bordered">
                  <thead>
                    <tr>
                      <th>Nombre</th>
                      <th>Apellido</th>
                      <th>Email</th>
                      <th>Permisos</th>
                      <th>Compañía</th>
                      <th colspan="3">Acciones</th>
                    </tr>
                  </thead>
                  <tbody>
                    <%@users.each do |user| %>
                      <tr>
                        <td><%=user.try(:first_name)%></td>
                        <td><%=user.try(:last_name)%></td>
                        <td><%=user.try(:email)%></td>
                        <td><%=bool_to_s_permissions(user)%></td>
                        <td><%=user.try(:company).try(:name)%></td>
                        <td><%= link_to 'Eliminar', delete_user_path(user), method: :delete, data: { confirm: 'Estas seguro?' }, class:"btn btn-danger" %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
                <br>
                <%= link_to 'Nuevo usuario', sign_up_path, class:'btn btn-success' %>
            </div>
        <br>
			</div><!--/.col-->
		</div><!--/.row-->
	</div>	<!--/.main-->

<p id="notice"><%= notice %></p>