config/routes.rb
Rails.application.routes.draw do
  mount Parse::Webhooks, at: '/webhooks'
  root 'home#index'

  resources :accidents
  resources :statuses
  resources :areas
  resources :employees
  resources :companies
  resources :nonconformities
  resources :company_notifications

  get 'finish_action/:id' => 'nonconformities#finish_action', as: 'finish_nonconformity'
  get 'finish_action_accident/:id' => 'accidents#finish_action', as: 'finish_accident'
  get 'users' => 'home#list_users'
  get 'logout' => 'user#end_session'
  get 'convert/:base64' => 'home#convert_base_64'
  get 'sign_in' => 'user#sign_in'
  get 'sign_up' => 'user#sign_up'

  post 'sign_up' => 'user#create_user'
  post 'sign_in' => 'user#create_session'

  delete 'eliminar-usuario/:id' => 'user#delete_user', as: 'delete_user'
end

app/models/company.rb
class Company < Parse::Object
  # See: https://github.com/modernistik/parse-stack#defining-properties

  # You can change the inferred Parse table/collection name below
  # parse_class "Company"

  property :name, :string
  property :description, :string
  property :email, :string
  has_many :areas
  has_many :employees
  has_many :users
  has_many :company_notifications
  # See: https://github.com/modernistik/parse-stack#cloud-code-webhooks
  # define a before save webhook for Company
  #webhook :before_save do
  #  company = parse_object
    # perform any validations with company
    # use `error!(msg)` to fail the save
    # ...
  #   company
  #end

  ## define an after save webhook for Company
  #
  # webhook :after_save do
  #   company = parse_object
  #
  # end

  ## define a before delete webhook for Company
  # webhook :before_delete do
  #   company = parse_object
  #   # use `error!(msg)` to fail the delete
  #   true # allow the deletion
  # end

  ## define an after delete webhook for Company
  # webhook :after_delete do
  #   company = parse_object
  # end

  ## Example of a CloudCode Webhook function
  ## define a `helloWorld` Parse CloudCode function
  # webhook :function, :helloWorld do
  #   "Hello!"
  # end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  layout 'admin'
  before_action :set_user
  before_action :set_company, only: %i[show edit update destroy]
  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @notifications = @company.company_notifications
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit; end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      @company.name = params[:company][:name]
      @company.description = params[:company][:description]
      @company.email = params[:company][:email]
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_company
    @company = Company.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def company_params
    data = {
      name: params[:company][:name],
      description: params[:company][:description],
      email: params[:company][:email]
    }
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
  <%= form_for @company do |form| %>

		<div class="container">
			<div class="row main">
				<div class="panel-heading">
				<div class="main-login main-center">
					<form class="form-horizontal" method="post" action="#">

						<div class="form-group">
							<label for="name" class="cols-sm-2 control-label">Nombre de la compañía</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="glyphicon glyphicon-info-sign" aria-hidden="true"></i></span>
                    <%= form.text_field :name, id: :company_name, class:"form-control", placeholder:'Nombre de la compañía' %>
								</div>
							</div>
						</div>

						<div class="form-group">
							<label for="email" class="cols-sm-2 control-label">Descripción de la compañía</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="glyphicon glyphicon-comment" aria-hidden="true"></i></span>
                    <%= form.text_area :description, class:"form-control", placeholder:'Descripción de la compañía', size:"2x5" %>
								</div>
							</div>
						</div>

						<div class="form-group">
							<label for="username" class="cols-sm-2 control-label">Email de la compañía</label>
							<div class="cols-sm-10">
								<div class="input-group">
									<span class="input-group-addon"><i class="glyphicon glyphicon-envelope" aria-hidden="true"></i></span>
                    <%= form.text_field :email, class:"form-control", placeholder:'Email de la compañía' %>
								</div>
							</div>
						</div>

						<div class="login-register">
                <%= form.submit 'Guardar', class:'btn btn-success'%>
                 <%= link_to 'Volver', companies_path, class:'btn btn-warning' %>
				    </div>
					</form>
				</div>
			</div>
		</div>
  <div class="actions">
    <br>
  </div>
<% end %>
  </div>

app/views/companies/edit.html.erb
  <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
				<li class=""><a href="<%=root_path%>">Inicio</a></li>
				<li class=""><a href="<%=companies_path%>">Compañías</a></li>
				<li class="active">Editar Compañía</li>
			</ol>
		</div><!--/.row-->

		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Editar Compañía</h1>
			</div>
		</div><!--/.row-->

<%= render 'form', company: @company %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
				<li class=""><a href="<%=root_path%>">Inicio</a></li>
				<li class="active">Compañías</li>
			</ol>
		</div><!--/.row-->

		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Compañías</h1>
			</div>
		</div><!--/.row-->

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Descripción</th>
      <th>Email</th>
      <th colspan="3">Acciones</th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.name %></td>
        <td><%= company.description %></td>
        <td><%= company.email %></td>
        <td><center><%= link_to 'Ver', company, class:'btn btn-success' %></td>
        <td><center><%= link_to 'Editar', edit_company_path(company), class:'btn btn-warning' %></td>
        <td><center><%= link_to 'Eliminar', company, method: :delete, data: { confirm: 'Estas seguro?' }, class:'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Añadir Compañía', new_company_path, class:'btn btn-success' %>

app/views/companies/new.html.erb
  <div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
				<li class=""><a href="<%=root_path%>">Inicio</a></li>
				<li class=""><a href="<%=companies_path%>">Compañías</a></li>
				<li class="active">Añadir Compañía</li>
			</ol>
		</div><!--/.row-->

		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Añadir Compañía</h1>
			</div>
		</div><!--/.row-->

<%= render 'form', company: @company %>

app/views/companies/show.html.erb
	<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">
		<div class="row">
			<ol class="breadcrumb">
				<li><a href="#"><svg class="glyph stroked home"><use xlink:href="#stroked-home"></use></svg></a></li>
				<li class=""><a href="<%=root_path%>">Inicio</a></li>
				<li class="active">Compañías</li>
			</ol>
		</div><!--/.row-->

		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">Compañías</h1>
			</div>
		</div><!--/.row-->

<div class="container">
      <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xs-offset-0 col-sm-offset-0 col-md-offset-3 col-lg-offset-3 toppad" >
          <div class="panel panel-info">
            <div class="panel-heading">
              <h3 class="panel-title"><%= @company.name  %></h3>
            </div>
            <div class="panel-body">
              <div class="row">
                <div class=" col-md-9 col-lg-9 ">
                  <table class="table table-user-information">
                    <tbody>
                      <tr>
                        <td>Descripción:</td>
                        <td><%= @company.description %></td>
                      </tr>
                    </tbody>
                  </table>
                </div>
               </div>
              </div>
             <div class="panel-footer">
              <%= link_to 'Editar', edit_company_path(@company), class:'btn btn-warning' %> | <%= link_to 'Volver', companies_path, class:'btn btn-danger' %>
          	</div>
          </div>
        </div>
      </div>
    </div>




      <div class="row">
        <div class="col-lg-12">
          <h1 class="page-header">Emails que reciben las notificaciones</h1>
        </div>
      </div><!--/.row-->
    <br>
    <%= link_to 'Añadir Email', new_company_notification_path, class:'btn btn-success' %>

      <table class="table table-bordered">
        <thead>
        <tr>
          <th>Nombre</th>
          <th>Email</th>
          <th colspan="3">Acciones</th>
        </tr>
        </thead>

        <tbody>
        <% @notifications.each do |notif| %>
            <tr>
              <td><%= notif.user.first_name %> <%= notif.user.last_name%></td>
              <td><%= notif.user.email %></td>
              <td><center><%= link_to 'Eliminar', notif, method: :delete, data: { confirm: 'Estas seguro?' }, class:'btn btn-danger' %></td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <br>